routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::namespace('Web')->group(function() {
    Route::get('/', ['uses' => 'LandingController@index', 'as' => '/']);

    Route::get('login', 'AuthController@getLogin');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['auth', 'role:superadministrator'])->prefix('admin')->group(function() {
        Route::get('/', 'AdminController@index')->name('admin.index');
        Route::resource('hierarchy', 'HeirarchyController', ['as' => 'admin']);
        Route::get('users/search', 'UserController@searchUser')->name('user.search');
        Route::post('user/bind', 'UserController@bind')->name('user.bind');
        Route::resource('users', 'UserController', ['as' => 'admin']);
        Route::resource('groups', 'GroupController', ['as' => 'admin']);

        Route::get('runsheets/{runsheetId}/leg/{legId}', 'RunsheetController@leg')->name('admin.leg.show');
        Route::post('runsheets/{runsheetId}/leg', 'LegController@store')->name('admin.runsheet.leg.store');
        Route::post('runsheets/{runsheetId}/leg/{legId}', 'LegController@legStore')->name('admin.runsheet.leg.field.store');
        Route::post('runsheets/{runsheetId}/publish', 'RunsheetController@published')->name('admin.runsheet.publish');
        Route::get('runsheets/{runsheet}/preview', 'RunsheetController@preview')->name('admin.runsheet.preview');

        Route::resource('runsheets', 'RunsheetController', ['as' => 'admin', 'except' => [
            'create',
        ]]);

        Route::get('leg/{id}/preview', 'LegController@preview')->name('admin.leg.preview');
        Route::resource('leg', 'LegController', ['as' => 'admin', 'except' => [
            'index',
            'store',
            'create',
            'destroy',
            'show'
        ]]);
    });
});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Group extends Model
{
    protected $table = 'groups';

    protected $fillable = [
    	'name',
    	'created_by',
        'description'
    ];

    protected $appends = [
        'total_members'
    ];

    protected function getTotalMembersAttribute()
    {
        return $this->users()->count();
    }

    public function groupHeads()
    {
    	return $this->where('is_head', true)->get();
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_group');
    }
}

app/Http/Controllers/Web/GroupController.php
<?php

namespace App\Http\Controllers\Web;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Web\AddGroupRequest;
use App\Group;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Group::all();

        return view('pages.admin.groups.index', compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddGroupRequest $request)
    {
        $authUser = get_auth_user();

        $group = Group::create([
            'name'        => $request->name,
            'description' => $request->description,
            'created_by'  => $authUser['id']
        ]);

        return back();
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $group = Group::with('users')->find($id);

        return view('pages.admin.groups.view', compact('group'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $group = Group::find($id);

        if (!$group) {
            return $this->setStatus(404)
                        ->setMessage('Not Found')
                        ->respond();
        }

        $group->delete();

        return $this->setMessage('Successfully Deleted')
                    ->respond();
    }
}

resources/views/pages/admin/groups/index.blade.php
@extends('layouts.admin')

@section('custom-style')
    <style type="text/css">
        .infos {
            margin-left:0;
        }
        .infos .name {
            color: black;
        }
    </style>
@endsection

@section('content')

    <div class="container">
        <div class="row">
            <h4 class="col m4 s12">
                Groups
                <img src="/img/search.svg" class="searchIcon"/>
            </h4>
            <h4 class="col m5 s12 push-m3 right-align">
                <a href="#addNew" class="modal-trigger waves-effect waves-light btn btn-medium primary-bg">+ New Group</a>
                <a class="waves-effect waves-light btn btn-medium green-bg">Import via Excel</a>
            </h4>
        </div>
        <div class="row">
            <div class="col s12">
                <table class="table-responsive modified">
                    <thead>
                        <tr>
                            <th>Name</th>
                            {{-- <th>Members</th> --}}
                            <th>Description</th>
                            <th class="center-align" width="230px">Actions</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($groups as $group)
                            <tr>
                                <td>
                                    <div class="infos">
                                        <h6 class="name">{{ $group->name }}</h6>
                                    </div>
                                </td>
                                {{-- <td>
                                    Member numbers
                                </td> --}}
                                <td>
                                    {{ $group->description }}
                                </td>
                                <td class="center-align">
                                    <a href="{{route('admin.groups.show', ['id' => $group->id])}}" class="btn-floating tooltipped no-shadow dark-gray-bg actionBtn" data-position="top" data-delay="50" data-tooltip="VIEW">
                                        <i class="material-icons">
                                            <img class="actionSvg" src="/img/view.svg"/>
                                        </i>
                                    </a>
                                    <button class="btn-floating tooltipped no-shadow dark-gray-bg actionBtn" data-position="top" data-delay="50" data-tooltip="EDIT">
                                        <i class="material-icons">
                                            <img class="actionSvg" src="/img/edit.svg"/>
                                        </i>
                                    </button>
                                    <a href="#deleteGroup" class="modal-trigger deleteGroupBtn btn-floating tooltipped no-shadow dark-gray-bg actionBtn" data-id="{{ $group->id }}"  data-position="top" data-delay="50" data-tooltip="DELETE">
                                        <i class="material-icons">
                                            <img class="actionSvg" src="/img/trash.svg"/>
                                        </i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <form id="addNew" class="modal" action="{{ route('admin.groups.store') }}" method="POST" role="form" enctype="multipart/form-data">
        <div class="modal-content">
            <h4>Group Details</h4>
            {{ csrf_field() }}
            <div class="row">
                <div class="input-field col s12">
                  <input name="name" id="dept_group" type="text" class="validate">
                  <label for="dept_group">Department / Group Name</label>
                </div>
                <div class="input-field col s12">
                  <textarea name="description" id="description" class="materialize-textarea validate"></textarea>
                  <label for="description">Description</label>
                </div>
            </div>
        </div>
        <div class="modal-footer input-field">
        <button type="submit" id="addGroup" href="#" class="modal-action modal-close waves-effect waves-green btn btn-medium primary-bg">Add Group</button>
        </div>
    </form>

    <div id="deleteGroup" class="modal">
        <div class="modal-content">
          <h4>Delete this group?</h4>
        </div>
        <div class="modal-footer">
          <a id="btn-deleteGroup" href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">Delete</a>
          <a href="#!" class="modal-action modal-close waves-effect btn-flat">Cancel</a>
        </div>
    </div>

@endsection

@section('addonjs')
    <script>
        $(document).ready(function(){
            /* Initializations */
            $('.modal').modal();
            $('select').material_select();
            
            var token = '{{ csrf_token()}}';

            $('#addGroup').click(function(){
                $('#addNew').modal('close');
                var toastContent = $('<span>Group Successfully Added!</span>');
                Materialize.toast(toastContent, 4000, 'green');
             });

            $('.deleteGroupBtn').click(function() {
                var group_id = $(this).data('id');
                $('#deleteGroup').data("id",group_id);
            });
            $('#deleteGroup #btn-deleteGroup').click(function() {
                $.ajax({
                    url: '/admin/groups/' + $('#deleteGroup').data('id'),
                    type: 'POST',
                    data: {
                        _method : 'DELETE',
                        _token : token
                    },
                    success: function(data) {
                        $('#deleteGroup').modal('close');
                        var toastContent = $('<span>Groups Successfully Deleted!</span>');
                        Materialize.toast(toastContent, 2000, 'red',function(){location.reload()});
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });
            });
            
        });
    </script>
@endsection

resources/views/pages/admin/groups/view.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <h4 class="col s12" style="margin-bottom: 0;">{{ $group->name }} <br/></h4>
    </div>
</div>

<nav class="profile-nav row">
    <div class="container">
        <ul class="tabs">
            <li class="tab"><a class="active" href="#infos">INFORMATION</a></li>
            <li class="tab"><a href="#members">MEMBERS</a></li>
            <li class="tab"><a href="#tasks">TASKS</a></li>
        </ul>
    </div>
</nav> 
<div class="row">
    <div class="container">
        <div id="infos" class="col s12">
            <table class="bordered">
                <tr>
                    <td class="title" width="200px">Group Name</td>
                    <td><strong>{{ $group->name }}</strong></td>
                </tr>
                <tr>
                    <td class="title">Group Description</td>
                    <td><strong>{{ $group->description }}</strong></td>
                </tr>
                <tr>
                    <td class="title">Total Users</td>
                    <td>{{ $group->total_members }}</td>
                </tr>
            </table>
        </div>

        <div id="members" class="col s12">
            <table class="col s12 centered modified task-table">
                <thead>
                    <tr>
                        <th width="200px">Username</th>
                        <th>Groups</th>
                        <th>Position</th>
                        <th>Email</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($group->users as $user)
                        <tr class="task">
                            <td>{{ $user->username }}</td>
                            <td>
                                @foreach($user->groups as $group)
                                    <div class="chip">
                                        {{ $group->name }}
                                    </div>
                                @endforeach
                            </td>
                            <td>{{ $user->role }}</td>
                            <td>{{ $user->email }}</td>
                            <td>
                                <a href="#" class="modal-trigger deleteGroupBtn btn-floating tooltipped no-shadow dark-gray-bg actionBtn" data-id="{{ $group->id }}"  data-position="top" data-delay="50" data-tooltip="DELETE">
                                    <i class="material-icons">
                                        <img class="actionSvg" src="/img/trash.svg"/>
                                    </i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div id="tasks">
            <div class="daily-tasks">
                <div class="col s5">
                    <h5>Daily Task List</h5>
                    <span>1 of 3 tasks completed</span>
                    <div class="progress green lighten-3">
                        <div class="determinate green darken-1" style="width: 30%"></div>
                    </div>
                </div>
                <table class="col s12 centered modified task-table">
                    <thead>
                        <tr>
                            <th style="min-width: 200px;">TASK</th>
                            <th>GROUP</th>
                            <th>STATUS</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="task">
                            <td>
                                <span class="name">Task name here</span>
                                <span class="sched">Scheduled for 22 Nov 2017</span>
                            </td>
                            <td>Eclair</td>
                            <td>
                                <span class="indicator late"></span>
                                <span class="status">Late for 2 days</span>
                            </td>
                        </tr>
                        <tr class="task">
                            <td>
                                <span class="name">Task name here</span>
                                <span class="sched">Scheduled for 22 Nov 2017</span>
                            </td>
                            <td>
                                <h6>Task Name Here</h6>
                            </td>
                            <td>
                                <span class="indicator done">
                                    <i class="material-icons">check</i>
                                </span>
                            </td>
                        </tr>
                        <tr class="task">
                            <td>Eclair</td>
                            <td>Eclair</td>
                            <td>
                                <span class="indicator pending"></span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection