routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::namespace('Web')->group(function() {
    Route::get('/', ['uses' => 'LandingController@index', 'as' => '/']);

    Route::get('login', 'AuthController@getLogin');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['auth', 'role:superadministrator'])->prefix('admin')->group(function() {
        Route::get('/', 'AdminController@index')->name('admin.index');
        Route::resource('hierarchy', 'HeirarchyController', ['as' => 'admin']);
        Route::get('users/search', 'UserController@searchUser')->name('user.search');
        Route::post('user/bind', 'UserController@bind')->name('user.bind');
        Route::resource('users', 'UserController', ['as' => 'admin']);
        Route::resource('groups', 'GroupController', ['as' => 'admin']);

        Route::get('runsheets/{runsheetId}/leg/{legId}', 'RunsheetController@leg')->name('admin.leg.show');
        Route::post('runsheets/{runsheetId}/leg', 'LegController@store')->name('admin.runsheet.leg.store');
        Route::post('runsheets/{runsheetId}/leg/{legId}', 'LegController@legStore')->name('admin.runsheet.leg.field.store');
        Route::post('runsheets/{runsheetId}/publish', 'RunsheetController@published')->name('admin.runsheet.publish');
        Route::get('runsheets/{runsheet}/preview', 'RunsheetController@preview')->name('admin.runsheet.preview');

        Route::resource('runsheets', 'RunsheetController', ['as' => 'admin', 'except' => [
            'create',
        ]]);

        Route::get('leg/{id}/preview', 'LegController@preview')->name('admin.leg.preview');
        Route::resource('leg', 'LegController', ['as' => 'admin', 'except' => [
            'index',
            'store',
            'create',
            'destroy',
            'show'
        ]]);
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;
use Laratrust\Traits\LaratrustUserTrait;
use App\Role;
use App\Leg;
use App\Group;

class User extends Authenticatable
{
    use HasApiTokens;
    use LaratrustUserTrait;
    use Notifiable;

    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'middle_name',
        'last_name',
        'phone_number',
        'email',
        'username',
        'password',
        'temporary_password',
        'account_image',
        'user_type',
        'address',
        'registered_by'
    ];

    /**
     * A list of attributes to be modified
     *
     * @var array
     */
    protected $appends = [
        'full_name',
        'name_initials',
        'role',
    ];

    /**
     * Returns Full Name Attribute
     *
     * @return string
     */
    protected function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * Returns the role in text
     *
     * @return string
     */
    protected function getRoleAttribute()
    {
        return $this->roles()->first()['name'];
    }

    /**
     * Returns the initial of the user
     *
     * @return string
     */
    protected function getNameInitialsAttribute()
    {
        $firstInitial = substr(strtoupper($this->first_name), 0, 1);
        $lastInitial = substr($this->last_name, 0, 1);

        $fullname =  $firstInitial . $lastInitial;

        return $fullname;
    }

    /**
     * Retuns the First name attributes in capital first
     *
     * @param string $value
     */
    public function setFirstNameAttribute($value)
    {
        $this->attributes['first_name'] = ucfirst($value);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function reciepientLeg()
    {
        return $this->belongsToMany(Leg::class, 'leg_reciepient');
    }

    public function senderLeg()
    {
        return $this->belongsToMany(Leg::class, 'leg_sender');
    }

    public function groups()
    {
        return $this->belongsToMany(Group::class, 'user_group');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Runsheet;
use App\Leg;
use Auth;

class UserController extends Controller
{
    public function me(Request $request)
    {
    	return $this->respond(get_auth_user());
    }

    public function runsheet()
    {
        $user = Auth::user();

        if (!is_null($user)) {
            $legs = $user->senderLeg()->get()->toArray();

            $runsheets = array_map(function($leg) {
                return [
                    'id'          => $leg['runsheet']['id'],
                    'name'        => $leg['runsheet']['name'],
                    'description' => $leg['runsheet']['description']
                ];
            }, $legs);

            return $this->respond($runsheets);
        }

        return $this->respond([]);
    }
}

app/Http/Controllers/Web/UserController.php
<?php

/**
 * @todo Clean up codes as in clean up your code mark
 * @todo Repository Pattern
 */

namespace App\Http\Controllers\Web;

use Illuminate\Http\Request;
use App\Http\Requests\Web\AddUserRequest;
use App\Http\Requests\Web\BindUserRequest;
use App\Http\Requests\Common\ImportExcelRequest;
use App\Http\Controllers\Controller;
use App\Jobs\User\SendWelcomeEmail;
use App\User;
use App\Role;
use App\Group;
use Storage;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $limit = $request->has('limit') ? $request->limit : '10';

        $roles = Role::where('name', '!=', 'superadministrator')->get();
        $groups = Group::all();
        $user = get_auth_user();
        $data = User::where('registered_by', $user['id'])
                    ->where('id', '!=', auth()->user()->id)
                    ->paginate($limit);

        return view('pages.admin.users.index', compact([
            'data', 'groups', 'roles'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::where('name', '!=', 'superadministrator')->get();
        $groups = Group::all();

        return view('pages.admin.users.create', compact([
            'roles', 'groups'
        ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddUserRequest $request)
    {
        $temporaryPassword = str_random(6);
        $userImage = $this->uploadImage($request->image, 'user_image');
        $authUser = get_auth_user();
        $groups = $request->groups;

        $input = [
            'first_name'         => ucfirst($request->first_name),
            'middle_name'        => ucfirst($request->middle_name),
            'last_name'          => ucfirst($request->last_name),
            'phone_number'       => $request->phone_number,
            'email'              => $request->email,
            'address'            => $request->address,
            'username'           => $request->username,
            'temporary_password' => $temporaryPassword,
            'password'           => bcrypt($temporaryPassword),
            'account_image'      => $userImage,
            'registered_by'      => $authUser['id'],
        ];

        $user = User::create($input);
        $role = Role::find($request->role);

        $user->attachRole($role);

        foreach($groups as $group) {
            $user->groups()->attach($group);
        }

        SendWelcomeEmail::dispatch($user);

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id)->toArray();

        if (!$user) {
            return redirect()->back()->with([
                'error' => 'Server error please contact provider'
            ]);
        }

        $image = '';

        if (filter_var($user['account_image'], FILTER_VALIDATE_URL)) {
            $image = $user['account_image'];
        } elseif ($user['account_image'] === '') {
            $image = 'https://picsum.photos/200/?random';
        } else {
            $image = asset($user['account_image']);
        }

        $user['account_image'] = $image;

        return view('pages.admin.users.view', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        if (!$user) {
            return $this->setStatus(500)
                        ->setMessage('Error')
                        ->respond();
        }

        return view('pages.admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        if (!$user) {
            return $this->setStatus(500)
                        ->setMessage('Error')
                        ->respond();
        }

        Storage::delete($user->account_image);

        $user = $user->delete();

        return $this->setMessage('Sucessfully Deleted')
                    ->respond();
    }

    /**
     * Import an excel file
     *
     * @param  ImportExcelRequest
     * @return \Illuminate\Http\Response
     */
    public function import(ImportExcelRequest $request)
    {
        $excel = $request->excel;

    }

    public function searchUser(Request $request)
    {
        $query = $request->has('search') ? $request->search : '';

        if ($query !== '') {
            return User::where('first_name', 'LIKE', '%'.$query.'%')
                       ->orWhere('last_name', 'LIKE', '%'.$query.'%')
                       ->where('user_type', '==', 'user')
                       ->limit(10)
                       ->get()
                       ->pluck('full_name', 'id');
        }

        return User::where('user_type', 'user')
                   ->limit(10)
                   ->get()
                   ->pluck('full_name', 'id');
    }

    public function bind(BindUserRequest $request)
    {
        $user = User::find($request->user);

        $user->groups()->attach($request->group);

        return $this->respond($user);
    }
}

resources/views/pages/admin/users/create.blade.php
<form action="{{ route('users.store') }}" method="POST" role="form" enctype="multipart/form-data">
    {{ csrf_field() }}

    <input type="file" name="image">

    <div class="form-group">
        <label for="">First Name</label>
        <input name="first_name" type="text" class="form-control" placeholder="First Name" required>
    </div>

    <div class="form-group">
        <label for="">Middle Name</label>
        <input name="middle_name" type="text" class="form-control" placeholder="Middle Name">
    </div>

    <div class="form-group">
        <label for="">Last Name</label>
        <input name="last_name" type="text" class="form-control" placeholder="Last Name" required>
    </div>

    <div class="form-group">
        <label for="">Phone Number</label>
        <input name="phone_number" type="text" class="form-control" placeholder="Phone Number" required>
    </div>

    <div class="form-group">
        <label for="">Email</label>
        <input name="email" type="email" class="form-control" placeholder="Email" required>
    </div>

    <div class="form-group">
        <label for="">Address</label>
        <textarea name="address" type="text" class="form-control" required></textarea>
    </div>

    <div class="form-group">
        <label for="">Username</label>
        <input name="username" type="text" class="form-control" placeholder="Username" required>
    </div>

    <div class="form-group">
        <label for="">Department/Group</label>
        <select name="group" id="input" class="form-control" required>
            @foreach($groups as $group)
                <option value="{{ $group->id }}">{{ $group->name }}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="">Role</label>
        <select name="role" id="input" class="form-control" required>
            @foreach($roles as $role)
                <option value="{{ $role->id }}">{{ $role->display_name }}</option>
            @endforeach
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

resources/views/pages/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
    @if ($errors->has('message'))
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success</strong> Successfully Added
        </div>
    @endif

    <div class="container">
        <div class="row">
            <h4 class="col l2 s6">
                User
                <img src="/img/search.svg" class="searchIcon"/>
            </h4>
            <h4 class="col l6 s6 push-l4 right-align">
                <a href="#addNew" class="modal-trigger waves-effect waves-light btn btn-medium primary-bg add-user">+ New User</a>
                <a href="#importUsers" class="modal-trigger waves-effect waves-light btn btn-medium green-bg">Import via Excel</a>
            </h4>
        </div>
        <div class="row">
            <table class="table-responsive modified">
                <thead>
                    <tr>
                        <th max-width="320px">Name</th>
                        <th>Group</th>
                        <th>Email</th>
                        <th class="center-align" max-width="250px">Actions</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($data as $user)
                    <tr>
                        <td>
                            @if ($user->account_image == '')
                                <div class="profile-image">{{$user->name_initials}}</div>
                            @else
                                <img src="{{ $user->account_image }}" style="float:left;width: 40px;" />
                            @endif
                            <div class="infos">
                                <h6 class="name">{{ $user->first_name . ' ' . $user->last_name }}</h6>
                                <span class="user_type">{{ $user->user_type }}</span>
                            </div>
                        </td>
                        <td>
                            @foreach ($user->groups as $group)
                                <div class="chip">
                                    {{ $group->name }}
                                </div>
                            @endforeach
                        </td>
                        <td>{{ $user->email }}</td>
                        <td class="center-align">
                            <a href="{{route('admin.users.show', ['id' => $user->id])}}" class="btn-floating tooltipped no-shadow dark-gray-bg actionBtn" data-position="top" data-delay="50" data-tooltip="VIEW">
                                <i class="material-icons">
                                    <img class="actionSvg" src="/img/view.svg"/>
                                </i>
                            </a>
                            <button class="btn-floating tooltipped no-shadow dark-gray-bg actionBtn" data-position="top" data-delay="50" data-tooltip="EDIT">
                                <i class="material-icons">
                                    <img class="actionSvg" src="/img/edit.svg"/>
                                </i>
                            </button>
                            <a href="#deleteUser" class="modal-trigger btn-floating tooltipped no-shadow dark-gray-bg actionBtn deleteUserBtn" data-position="top" data-id="{{$user->id}}" data-delay="50" data-tooltip="DELETE">
                                <i class="material-icons">
                                    <img class="actionSvg" src="/img/trash.svg"/>
                                </i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <form action="{{ route('admin.users.store') }}" method="POST" role="form" enctype="multipart/form-data" id="addNew" class="modal" style="padding-bottom: 20px">
        {{ csrf_field() }}
        @if(!$groups)
            <div class="modal-content">
                <h4>Cannot add user</h4>
                <p>You have an empty groups. Fill out atleast one to create user.</p>
            </div>
            <div class="modal-footer">
                <a href="{{ url('/admin/groups') }}" class="waves-effect waves-light btn btn-medium primary-bg">Add Group</a>
            </div>
        @else
            <div class="part-1">
                <div class="modal-content">
                    <h4>Personal Details</h4>
                    <div class="row">
                        <div class="input-field col s12">
                            <input name="first_name" id="first_name" type="text" class="validate">
                            <label for="first_name">First Name</label>
                        </div>
                        <div class="input-field col s12">
                          <input name="middle_name" id="sfx_name" type="text" class="validate" value="">
                          <label for="sfx_name">Middle Name</label>
                        </div>
                        <div class="input-field col s12">
                          <input name="last_name" id="last_name" type="text" class="validate">
                          <label for="last_name">Last Name</label>
                        </div>
                        <div class="input-field col s12">
                          <input name="phone_number" id="c_num" type="text" class="validate">
                          <label for="c_num">Contact Number</label>
                        </div>
                        <div class="input-field col s12">
                          <input name="email" id="email" type="email" class="validate">
                          <label for="email">Email</label>
                        </div>
                        <div class="input-field col s12">
                          <input name="address" id="address" type="text" class="validate">
                          <label for="address">Address</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <div class="input-field col s12">
                            <a id="addNewNext" href="#" class="waves-effect waves-light btn btn-medium primary-bg">Next</a>
                            <a href="#" class="add-cancel modal-action modal-close waves-effect waves-light btn btn-medium red lighten-1">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="part-2">
                <div class="modal-content">
                    <h4>User Account Details</h4>
                    <div class="row">
                        <div class="input-field col s12">
                            <input name="username" id="username" type="text" class="validate">
                            <label for="username">Username</label>
                        </div>
                        <div class="input-field col s8">
                            <select name="groups[]" id="dept_group" multiple>
                                <option value="" disabled selected>Choose your option</option>
                                @foreach($groups as $group)
                                    <option value="{{ $group->id }}">{{ $group->name }}</option>
                                @endforeach
                            </select>
                            <label for="dept_group">Department / Group</label>
                        </div>
                        <div class="input-field col s4">
                            <select name="role" id="role">
                                @foreach($roles as $role)
                                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                            <label for="role">Role</label>
                        </div>
                        <div class="input-field col s12">
                            <input id="new_dept_group" type="text" class="validate">
                            <label for="new_dept_group">or add a new department or group</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer row">
                    <div class="input-field col s6 center-align">
                        <a id="addNewBack" href="#" class="waves-effect waves-green btn btn-medium grey">Back</a>
                    </div>
                    <div class="input-field col s6 center-align">
                        <button type="submit" id="btn-add" href="#" class="modal-action modal-close waves-effect waves-blue-grey btn btn-medium primary-bg">Add User</button>
                        <a href="#" class="add-cancel modal-action modal-close waves-effect waves-light btn btn-medium red lighten-1">Cancel</a>
                    </div>
                </div>
            </div>
        @endif
    </form>

    <div id="importUsers" class="modal">
        <div class="modal-content">
            <h4>Import Users</h4>
            <div class="file-field input-field">
                <div class="btn">
                    <span>Excel File</span>
                    <input type="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
                </div>
                <div class="file-path-wrapper">
                    <input class="file-path validate" type="text" placeholder="Upload one or more files">
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <a id="btn-delete" href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">Delete</a>
          <a href="#!" class="modal-action modal-close waves-effect btn-flat">Cancel</a>
        </div>
    </div>

    <div id="deleteUser" class="modal">
        <div class="modal-content">
          <h4>Delete this user?</h4>
        </div>
        <div class="modal-footer">
          <a id="btn-delete" href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">Delete</a>
          <a href="#!" class="modal-action modal-close waves-effect btn-flat">Cancel</a>
        </div>
    </div>
@endsection

@section('addonjs')
    <script>
        $(document).ready(function(){
            var token = '{{ csrf_token()}}';

            /* Initializations */
            $('.modal').modal({
                dismissible: false
            });
            $('select').material_select();

            // Get Modal Width
            var modalWidth = $('#addNew').width();
            $('#addNewNext').click(function(){
                $("#addNew .part-1").animate({width: 0+'px' }).hide();
                $("#addNew .part-2").animate({width: modalWidth+'px' }).show();
            });
            $('#addNewBack').click(function(){
                $("#addNew .part-1").animate({width: modalWidth - 7 +'px' }).show();
                $("#addNew .part-2").animate({width: 0+'px' }).hide();
            });
            $('a.add-cancel').click(function() {
                $("#addNew .part-2").animate({width: 0+'px' }).hide();
                $("#addNew .part-1").animate({width: modalWidth - 7 +'px' }).show();
            });

            $('.deleteUserBtn').click(function() {
                var user_id = $(this).data('id');
                $('#deleteUser').data("id",user_id);
            });

            $('#deleteUser #btn-delete').click(function() {
                $.ajax({
                    url: '/admin/users/' + $('#deleteUser').data('id'),
                    type: 'POST',
                    data: {
                        _method : 'DELETE',
                        _token : token
                    },
                    success: function(data) {
                        var toastContent = $('<span>User Successfully Deleted!</span>');
                        Materialize.toast(toastContent, 2000, 'red',function(){location.reload()});
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });
            });
        });
    </script>
@endsection