routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::namespace('Web')->group(function() {
    Route::get('/', ['uses' => 'LandingController@index', 'as' => '/']);

    Route::get('login', 'AuthController@getLogin');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['auth', 'role:superadministrator'])->prefix('admin')->group(function() {
        Route::get('/', 'AdminController@index')->name('admin.index');
        Route::resource('hierarchy', 'HeirarchyController', ['as' => 'admin']);
        Route::get('users/search', 'UserController@searchUser')->name('user.search');
        Route::post('user/bind', 'UserController@bind')->name('user.bind');
        Route::resource('users', 'UserController', ['as' => 'admin']);
        Route::resource('groups', 'GroupController', ['as' => 'admin']);

        Route::get('runsheets/{runsheetId}/leg/{legId}', 'RunsheetController@leg')->name('admin.leg.show');
        Route::post('runsheets/{runsheetId}/leg', 'LegController@store')->name('admin.runsheet.leg.store');
        Route::post('runsheets/{runsheetId}/leg/{legId}', 'LegController@legStore')->name('admin.runsheet.leg.field.store');
        Route::post('runsheets/{runsheetId}/publish', 'RunsheetController@published')->name('admin.runsheet.publish');
        Route::get('runsheets/{runsheet}/preview', 'RunsheetController@preview')->name('admin.runsheet.preview');

        Route::resource('runsheets', 'RunsheetController', ['as' => 'admin', 'except' => [
            'create',
        ]]);

        Route::get('leg/{id}/preview', 'LegController@preview')->name('admin.leg.preview');
        Route::resource('leg', 'LegController', ['as' => 'admin', 'except' => [
            'index',
            'store',
            'create',
            'destroy',
            'show'
        ]]);
    });
});

app/Runsheet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Leg;
use App\User;

class Runsheet extends Model
{
    protected $table = 'runsheets';

    protected $fillable = [
        'name',
        'table_name',
        'created_by',
        'is_published',
        'description'
    ];

    public function legs()
    {
        return $this->hasMany(Leg::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Web/RunsheetController.php
<?php

namespace App\Http\Controllers\Web;

use Illuminate\Http\Request;
use App\Http\Requests\Web\AddRunsheetRequest;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use App\Http\Controllers\Controller;
use App\Runsheet;
use App\Leg;
use App\User;

class RunsheetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $runsheet = Runsheet::all();
        return view('pages.admin.runsheets.index', compact('runsheet'));
    }

    /**
     * Returns a single leg from a runsheet
     * @param  int $runsheetId
     * @param  int $legId
     * @return \Illuminate\Http\Response
     */
    public function leg($runsheetId, $legId)
    {
        $leg = Leg::find($legId);

        if (!$leg) {
            return redirect(route('admin.runsheets.index'));
        }

        return view('pages.admin.runsheets.leg', compact('leg'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($runsheetId, $legId)
    {
        return view('pages.admin.runsheets.view');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddRunsheetRequest $request)
    {
        $tableDescriptionName = str_replace(' ', '_', strtolower($request->name)) . '_description';

        $input = [
            'name'                   => $request->name,
            'description'            => $request->description,
            'created_by'             => 1,
        ];

        $runsheet = Runsheet::create($input);

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $runsheet = Runsheet::find($id);
        $leg = Leg::where('runsheet_id',$id)->get();
        $users = User::get();

        if (!$runsheet) {
            return redirect(route('admin.runsheets.index'));
        }

        return view('pages.admin.runsheets.view' , compact('runsheet','leg','users'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $runsheet = Runsheet::find($id);

        if ($runsheet) {
            Schema::dropIfExists($runsheet->table_description_name);

            $runsheet->delete();
            return $this->respond($runsheet->toArray());
        }

        return $this->repond500();
    }

    /**
     * Publishes the runsheet
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function published($id)
    {
        $runsheet = Runsheet::find($id);

        if (count($runsheet->legs) == 0) {
            return $this->setMessage('Cannot publish no legs found')
                        ->respond500();
        }

        foreach ($runsheet->legs as $leg) {
            $fields = $leg->fields;
            Schema::table($leg->leg_table_name, function(Blueprint $table) use ($fields) {
                foreach($fields as $field) {
                    $table->string(str_replace(' ', '_', strtolower($field['name'])))->after('id');
                }
            });
        }

        $runsheet->update([
            'is_published' => true
        ]);

        return $this->respond($runsheet->toArray());
    }

    /**
     * Returns the preview of the runsheet
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function preview($id)
    {
        $result = [];
        $runsheet = Runsheet::find($id);
        $legs = Leg::where('runsheet_id', $id)
                   ->get()
                   ->toArray();

        $result['id'] = $runsheet->id;
        $result['name'] = $runsheet->name;
        $result['legs'] = array_map(function($leg) {
            return [
                'id'     => $leg['id'],
                'name'   => $leg['name'],
                'fields' => $leg['fields'],
            ];
        }, $legs);


        return $this->respond($result);
    }
}

resources/views/pages/admin/runsheets/index.blade.php
@extends('layouts.admin')

@section('custom-style')
	<style type="text/css">
		.runsheet-filter {
			padding: 0px 5px;
			box-shadow: unset !important;
			border: 1px solid #78909c;
		}
		.empty-runsheet {
			display: flex;
			flex-direction: column;
			align-items: center;
			font-size: 1.25em;
			color: #78909c;
		}
		.empty-runsheet img {
			width: 80px;
		}
		.empty-runsheet p {
			font-size: .75em;
			margin: 0;
		}
		.card .right img {
			width: 20px;
			pointer-events: none;
		}
		.chip.pblsh {
			color: white;
			background-color: #43b62e;
			text-transform: uppercase;
		}
		.chip.inprog {
			color: white;
			background-color: #e5c90d;
			text-transform: uppercase;
		}
		.runsheet .card-content {
			padding:30px;
		}
		.runsheet-content {
			margin-top: 30px;
			text-align: center;
		}
		.runsheet-title {
			font-size: 1.25em;
		}
		.runsheet-group {
			color: #26a69a;
		}
		.runsheet-date {
			color: #7a7a7a;
		}
		.runsheet-info {
			color: #7a7a7a;
			margin-top: 30px;
		}
		.card-footer {
			padding: 20px 0;
		}
		.card-footer a {
			color: black;
		}
		.dropdown-content {
			width: initial !important;
		}
		.runsheet-filtered .chip.primary-bg {
			color: white;
		}
		.modal {
			top: 5%;
			max-height: 80%;
		}
		#pubRunsheet,
		#delRunsheet {
			width: 33%;
		}
		#pubRunsheet .modal-footer,
		#delRunsheet .modal-footer {
			text-align: center;
		}
		#prevRunsheet {
			width: 80%;
		}
		#prevRunsheet .modal-content {
			pointer-events: none;
		}
	</style>
@endsection

@section('content')
	<div class="container">
        <div class="row">
            <h4 class="col l2 s6"> Runsheets </h4>
            <h4 class="col l6 s6 push-l4 right-align">
                <a href="#addNewRunsheet" class="modal-trigger waves-effect waves-light btn btn-medium primary-bg">+ Create Runsheet</a>
                <a href="#" class="btn dropdown-button transparent runsheet-filter" data-activates='runsheet-filter'><img src="/img/filter.svg"></a>
            </h4>
        </div>
        @if(count($runsheet) >= 1)
		    <div class="row">
	        	@foreach ($runsheet as $r)
		        	<div class="col s4">
			        	<div class="card runsheet">
						    <div class="card-content">
						    	<span class="card-title grey-text text-darken-4">
						    		@if(!$r->is_published)
						      		<a href="#" class="dropdown-button material-icons right" data-activates='runsheet-action-{{$r->id}}'><img src="/img/more.svg"></a>
									<ul id='runsheet-action-{{$r->id}}' class='dropdown-content'>
									    <li><a href="#!" data-id="{{$r->id}}">EDIT</a></li>
									    <li><a href="#delRunsheet" data-id="{{$r->id}}" class="modal-trigger delRunsheetBtn" data-bind="{{$r->id}}">DELETE</a></li>
									</ul>
									@endif
									
									@if($r->is_published)
							      		<div class="chip pblsh">Published</div>
						      		@else
							      		<div class="chip inprog">In Progress</div>
						      		@endif
						      	</span>
						      	<div class="runsheet-content">
								    <h6 class="runsheet-title">{{$r->name}}</h6>
								    {{-- <div class="runsheet-group">Marketing Group</div> --}}
								    <div class="runsheet-date">Created {{$r->created_at->diffForHumans()}}</div>
								    <div class="runsheet-info">{{$r->description}}</div>
						      	</div>

					      		@if($r->is_published)
						      	<div class="card-footer center-align">
					      			<a href="#prevRunsheet" class="modal-trigger prevRunsheetBtn" data-id="{{$r->id}}">PREVIEW</a>
					      		@else
					      		<div class="card-footer">
					      			<a href="#pubRunsheet" class="modal-trigger btn-pub" data-id="{{$r->id}}">PUBLISH</a>
					      			<a href="{{ route('admin.runsheets.show', ['runsheet' => $r->id]) }}" class="right">VIEW</a>
					      		@endif
						      	</div>
						    </div>
						</div>
		        	</div>
				@endforeach
	        </div>
        @else
	        <div class="row empty-runsheet">
	        	<img src="/img/empty-runsheet.svg">
	        	<h5>You have not created any Runsheets.</h5>
	        	<p>Organize your legs and create your runsheets now.</p>
	        	<p>Click 'Create Runsheets' at the top right corner.</p>
	        </div>
        @endif
        {{-- 
	        <div class="row runsheet-filtered">
	        	<div class="chip transparent"> Filter </div>
				<div class="chip primary-bg">
				    Published
				    <i class="close material-icons">close</i>
				</div>
	        </div>
        --}}
        
        {{--
	        <div class="row">
	        	<ul class="pagination right">
				    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
				    <li class="active"><a href="#!">1</a></li>
				    <li class="waves-effect"><a href="#!">2</a></li>
				    <li class="waves-effect"><a href="#!">3</a></li>
				    <li class="waves-effect"><a href="#!">4</a></li>
				    <li class="waves-effect"><a href="#!">5</a></li>
				    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
				  </ul>
	        </div>
        --}}
    </div>
	<ul id='runsheet-filter' class='dropdown-content'>
	    <li><a href="#!">NO FILTER</a></li>
	    <li><a href="#!">PUBLISHED</a></li>
	    <li><a href="#!">IN PROGRESS</a></li>
	</ul>
	<form id="addNewRunsheet" class="modal" action="{{ route('admin.runsheets.store') }}" method="POST" role="form" enctype="multipart/form-data">
	    <div class="modal-content">
	    	<h4>Runsheet Details</h4>
	    	{{ csrf_field() }}
	    	<div class="row">
	            <div class="input-field col s12">
	                <input name="name" type="text" />
	                <label class="active">Name of Runsheet</label>
	            </div>
	        </div>
	    	<div class="row">
	            <div class="input-field col s12">
	                <input name="description" type="text" />
	                <label class="active">Runsheet Description</label>
	            </div>
	        </div>
	    </div>
	    <div class="modal-footer">
	    	<div class="row">
	            <div class="input-field col s12">
	                <button type="submit" id="btn-addRunsheet" href="#" class="modal-action modal-close waves-effect waves-blue-grey btn btn-medium primary-bg">Create Runsheet</button>
	            </div>
            </div>
	    </div>
	</form>
	<div id="prevRunsheet" class="modal">
	    <div class="modal-content">
	    	<h5>Preview</h5>
	    	<div class="leg-content-inner"></div>
	    </div>
	    <div class="modal-footer center-align">
            <a href="#" class="modal-action modal-close waves-effect waves-blue-grey btn btn-medium green">Close Preview</a>
	    </div>
	</div>
	<div id="delRunsheet" class="modal center-align">
	    <div class="modal-content">
	    	<h5>Your about to delete a runsheet.</h5>
	    	<p>Are you sure you want to delete this</p>
	    	<p>If not, click the outside of this box to exit.</p>
	    </div>
	    <div class="modal-footer center-align">
            <a id="btn-delRunsheet" href="#" class="modal-action modal-close waves-effect waves-blue-grey btn btn-medium red">Delete Runsheet</a>
	    </div>
	</div>
	<div id="pubRunsheet" class="modal center-align">
	    <div class="modal-content">
	    	<h5>Your about to publish a runsheet.</h5>
	    	<p>Are you sure you want to publish this</p>
	    	<p>If not, click the outside of this box to exit.</p>
	    </div>
	    <div class="modal-footer center-align">
            <a id="btn-pubRunsheet" href="#" class="modal-action modal-close waves-effect waves-blue-grey btn btn-medium green">Publish Runsheet</a>
	    </div>
	</div>
@endsection

@section('addonjs')
    <script>
        $(document).ready(function(){
            $('.modal').modal();
            var token = '{{ csrf_token()}}';
            $('#btn-addRunsheet').click(function(){
                var toastContent = $('<span>Runsheet Created Successfully</span>');
                Materialize.toast(toastContent, 4000, 'green');
            });
            $('.btn-pub').click(function() {
                var runsheet_id = $(this).data('id');
                $('#pubRunsheet').data("id",runsheet_id);
            });
            $('#btn-pubRunsheet').click(function() {
                $.ajax({
                    url: '/admin/runsheets/' + $('#pubRunsheet').data('id') + '/publish',
                    type: 'POST',
                    data: {
                        _token : token
                    },
                    success: function(data) {
                        $('#pubRunsheet').modal('close');
                        var toastContent = $('<span>Runsheet Successfully Published!</span>');
                        Materialize.toast(toastContent, 2000, 'green',function(){location.reload()});
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });
            });
            $('.prevRunsheetBtn').click(function() {
            	$.ajax({
				   	type: 'GET',
				   	url: '/admin/runsheets/' + $(this).data('id') + '/preview',
				   	beforeSend: function(){
				   		$('#prevRunsheet .leg-content-inner').empty();
				   		$('#prevRunsheet .modal-content').append('<div class="progress">\
						      <div class="indeterminate"></div>\
						  </div>');
				   	},
				   	success: function(res) {
				   		$('#prevRunsheet .progress').remove();
				   		var legs = '',
				   			legs_id= '',
				   			fields = '',
				   			title = '';
				   		$.each(res.data.legs, function(key,leg){
				   			legs_id = "leg"+leg.id;
				   			legs = '<div id="'+legs_id+'"><h5>' + leg.name + '</h5></div>';
				   			$('#prevRunsheet .leg-content-inner').append(legs);

							console.log(leg);
				   			if(!leg.fields.length > 0){
								$('#'+legs_id).append('No Leg Fields Found');
							}else{
							    runsheetPreview(legs_id,leg);
							}
				   		});
				   	},
				   	error: function(data) {
				   		$('#prevRunsheet .progress').remove();
				     	console.log(data);
				   	}
				});
            });
            $('.delRunsheetBtn').click(function() {
                var runsheet_id = $(this).data('id');
                $('#delRunsheet').data("id",runsheet_id);
            });
            $('#delRunsheet #btn-delRunsheet').click(function() {
                $.ajax({
                    url: '/admin/runsheets/' + $('#delRunsheet').data('id'),
                    type: 'POST',
                    data: {
                        _method : 'DELETE',
                        _token : token
                    },
                    success: function(data) {
                        $('#delRunsheet').modal('close');
                        var toastContent = $('<span>Runsheet Successfully Deleted!</span>');
                        Materialize.toast(toastContent, 2000, 'red',function(){location.reload()});
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });
            });
        });
    </script>
@endsection

resources/views/pages/admin/runsheets/leg.blade.php
<!DOCTYPE html>
<html>
    <head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="csrf-token" content="{{ csrf_token() }}">
	    <title>NorthpoleTech | Leg</title>
	    <link rel="shortcut icon" href="/img/favicon.ico" />
	    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
	    <!-- Styles -->
	    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
	    <style type="text/css">
	    	#previewLeg{
	    		width: 80%;
	    	}
	    	#previewLeg .leg-content-inner{
	    		pointer-events: none;
	    	}
	    </style>
	</head>
	<body>
		<div class="row leg-view">
	      	<div class="col s3 sidebar">
	    		<a href="{{ route('admin.runsheets.show', ['runsheet' => $leg->runsheet_id]) }}" class="btn-back">
	    			<i class="fa fa-long-arrow-left"></i>
	    			<span>Go Back</span>
	    		</a>
			    <div class="col s12 navtabs">
			      <ul class="tabs tabs-fixed-width">
			        <li class="tab col s3"><a class="active" href="#leg-fields">FIELDS</a></li>
			        <li class="tab col s3"><a href="#leg-setting">SETTINGS</a></li>
			      </ul>
			    </div>
			    <div id="leg-fields" class="col s12">
			    	<div class="field-leg field-leg-source field-checkbox">
			    		<i class="fa fa-check-square-o"></i>
			    		<span class="field-title">Checkbox</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-date">
			    		<i class="fa fa-calendar-o"></i>
			    		<span class="field-title">Date</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-select">
			    		<i class="fa fa-caret-down"></i>
			    		<span class="field-title">Dropdown</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-multiline">
			    		<i class="fa fa-align-justify"></i>
			    		<span class="field-title">Multiple Line</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-notes">
			    		<i class="fa fa-sticky-note"></i>
			    		<span class="field-title">Notes</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-number">
			    		<i class="fa fa-hashtag"></i>
			    		<span class="field-title">Number</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-radio">
			    		<i class="fa fa-circle-o"></i>
			    		<span class="field-title">Radio Button</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-signature">
			    		<i class="fa fa-pencil"></i>
			    		<span class="field-title">Signature</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-singleline">
			    		<i class="fa fa-minus"></i>
			    		<span class="field-title">Single Line</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-time">
			    		<i class="fa fa-clock-o"></i>
			    		<span class="field-title">Time</span>
			    	</div>
			    	<div class="field-leg field-leg-source field-upload">
			    		<i class="fa fa-image"></i>
			    		<span class="field-title">Upload Image</span>
			    	</div>
			    </div>
			    <div id="leg-setting" class="col s12">
			    	{{-- Settings --}}
			    </div>
	      	</div>

	      	<div id="leg-main-content" class="col s9">
	      		<div class="row">
		        	<div class="col l8 leg-title">
		            	<h4>{{$leg->name}}</h4>
		            	<p>Updated {{$leg->updated_at->diffForHumans()}}</p>
		            </div>
		            <h4 class="col l4 right-align">
		            	<div class="row">
		            		<div class="col s6">
		               			<a href="#previewLeg" class="modal-trigger waves-effect waves-light btn btn-medium transparent leg-preview">
		               				<img src="/img/view.svg"/>
			               			<span>Preview</span>
			               		</a>
		               		</div>
		            		<div class="col s6">
		            			<a id="saveLegField" href="#" class="modal-trigger waves-effect waves-light btn btn-medium primary-bg leg-save">
		            				<i class="material-icons">check</i>
		            				<span>Save Leg</span>
		            			</a>
		            		</div>
		            	</div>
		            </h4>
	            </div>
		        <div class="row">
		        	<div id="leg-content" class="col s12 leg-content-inner">
		        		<div class="card leg loading-leg-field center-align">
		        			<div class="preloader-wrapper big active">
							    <div class="spinner-layer spinner-blue-only">
							      	<div class="circle-clipper left">
							        	<div class="circle"></div>
							      	</div>
							      	<div class="gap-patch">
							        	<div class="circle"></div>
							      	</div>
						      		<div class="circle-clipper right">
						        		<div class="circle"></div>
						      		</div>
						    	</div>
						  	</div>
		        			<h6>Loading Legs</h6>
		        		</div>
		        		<div class="card leg empty-leg-field center-align" style="display: none">
		        			<h6>You have no fields</h6>
		        			<p>Drag and Drop fields to give body to your form.</p>
		        			<p>Edit the field by going to the settings tab.</p>
		        		</div>
		        		{{-- Add class 'leg-field-preseted' for edit --}}
		        	</div>
		        </div>
	      	</div>
	    </div>
	    <div id="previewLeg" class="modal">
		    <div class="modal-content leg-content-inner">
		    	<h5>Preview</h5>
		    </div>
		    <div class="modal-footer center-align">
	            <a href="#" class="modal-action modal-close waves-effect waves-blue-grey btn btn-medium green">Close Preview</a>
		    </div>
		</div>
	</body>
	<script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$('.modal').modal();
			$.ajax({
			   	type: 'GET',
			   	url: '/admin/leg/' + {{$leg->id}} + '/preview',
			   	beforeSend: function(){
					$('.empty-leg-field').hide();
					$('.loading-leg-field').show();
			   	},
			   	success: function(data) {
			   		console.log(data.data);
					$('.loading-leg-field').hide();
			     	if(!data.data.fields.length > 0){
					    $('.empty-leg-field').show();
					}else{
					    runsheetEdit(data.data);
					}
			   	},
			   	error: function(data) {
			     	console.log(data);
			   	}
			});
		    
			var token = '{{ csrf_token()}}';
			var url = "{{ route('admin.runsheet.leg.field.store', ['runsheetID' => $leg->runsheet_id, 'legId' => $leg->id]) }}";

			runsheetSave(token,url);
			
			$('.leg-preview').click(function(){
				$('#previewLeg').find('.leg-field-delete').remove();
			});
		});
	</script>
	
</html>